/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPredictionMarket,
  IPredictionMarketInterface,
} from "../../interfaces/IPredictionMarket";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "matchId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "homeTeam",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "awayTeam",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "kickoffTimestamp",
        type: "uint64",
      },
    ],
    name: "MatchCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "matchId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum IPredictionMarket.Outcome",
        name: "result",
        type: "uint8",
      },
    ],
    name: "MatchResolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "matchId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "predictor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "points",
        type: "uint256",
      },
    ],
    name: "PointsAwarded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "matchId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "predictor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum IPredictionMarket.Outcome",
        name: "pick",
        type: "uint8",
      },
    ],
    name: "PredictionSubmitted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "matchId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "homeTeam",
        type: "string",
      },
      {
        internalType: "string",
        name: "awayTeam",
        type: "string",
      },
      {
        internalType: "uint64",
        name: "kickoffTimestamp",
        type: "uint64",
      },
    ],
    name: "createMatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "predictor",
        type: "address",
      },
    ],
    name: "getLeaderboardScore",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "matchId",
        type: "bytes32",
      },
      {
        internalType: "enum IPredictionMarket.Outcome",
        name: "result",
        type: "uint8",
      },
    ],
    name: "resolveMatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "matchId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "predictor",
        type: "address",
      },
    ],
    name: "scorePredictor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "matchId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "homeTeam",
        type: "string",
      },
      {
        internalType: "string",
        name: "awayTeam",
        type: "string",
      },
      {
        internalType: "uint64",
        name: "kickoffTimestamp",
        type: "uint64",
      },
      {
        internalType: "enum IPredictionMarket.Outcome",
        name: "pick",
        type: "uint8",
      },
    ],
    name: "submitPrediction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPredictionMarket__factory {
  static readonly abi = _abi;
  static createInterface(): IPredictionMarketInterface {
    return new Interface(_abi) as IPredictionMarketInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPredictionMarket {
    return new Contract(address, _abi, runner) as unknown as IPredictionMarket;
  }
}
