/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { PredictionMarket } from "./PredictionMarket";
export * as factories from "./factories";
export type { IPredictionMarket } from "./interfaces/IPredictionMarket";
export { IPredictionMarket__factory } from "./factories/interfaces/IPredictionMarket__factory";
export { PredictionMarket__factory } from "./factories/PredictionMarket__factory";
