/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IPredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createMatch"
      | "getLeaderboardScore"
      | "resolveMatch"
      | "scorePredictor"
      | "submitPrediction"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchCreated"
      | "MatchResolved"
      | "PointsAwarded"
      | "PredictionSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createMatch",
    values: [BytesLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboardScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMatch",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scorePredictor",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPrediction",
    values: [BytesLike, string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboardScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scorePredictor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPrediction",
    data: BytesLike
  ): Result;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    homeTeam: string,
    awayTeam: string,
    kickoffTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    matchId: string,
    homeTeam: string,
    awayTeam: string,
    kickoffTimestamp: bigint
  ];
  export interface OutputObject {
    matchId: string;
    homeTeam: string;
    awayTeam: string;
    kickoffTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchResolvedEvent {
  export type InputTuple = [matchId: BytesLike, result: BigNumberish];
  export type OutputTuple = [matchId: string, result: bigint];
  export interface OutputObject {
    matchId: string;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsAwardedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    predictor: AddressLike,
    points: BigNumberish
  ];
  export type OutputTuple = [
    matchId: string,
    predictor: string,
    points: bigint
  ];
  export interface OutputObject {
    matchId: string;
    predictor: string;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionSubmittedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    predictor: AddressLike,
    pick: BigNumberish
  ];
  export type OutputTuple = [matchId: string, predictor: string, pick: bigint];
  export interface OutputObject {
    matchId: string;
    predictor: string;
    pick: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): IPredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: IPredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createMatch: TypedContractMethod<
    [
      matchId: BytesLike,
      homeTeam: string,
      awayTeam: string,
      kickoffTimestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getLeaderboardScore: TypedContractMethod<
    [predictor: AddressLike],
    [bigint],
    "view"
  >;

  resolveMatch: TypedContractMethod<
    [matchId: BytesLike, result: BigNumberish],
    [void],
    "nonpayable"
  >;

  scorePredictor: TypedContractMethod<
    [matchId: BytesLike, predictor: AddressLike],
    [void],
    "nonpayable"
  >;

  submitPrediction: TypedContractMethod<
    [
      matchId: BytesLike,
      homeTeam: string,
      awayTeam: string,
      kickoffTimestamp: BigNumberish,
      pick: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<
    [
      matchId: BytesLike,
      homeTeam: string,
      awayTeam: string,
      kickoffTimestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLeaderboardScore"
  ): TypedContractMethod<[predictor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolveMatch"
  ): TypedContractMethod<
    [matchId: BytesLike, result: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scorePredictor"
  ): TypedContractMethod<
    [matchId: BytesLike, predictor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitPrediction"
  ): TypedContractMethod<
    [
      matchId: BytesLike,
      homeTeam: string,
      awayTeam: string,
      kickoffTimestamp: BigNumberish,
      pick: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchResolved"
  ): TypedContractEvent<
    MatchResolvedEvent.InputTuple,
    MatchResolvedEvent.OutputTuple,
    MatchResolvedEvent.OutputObject
  >;
  getEvent(
    key: "PointsAwarded"
  ): TypedContractEvent<
    PointsAwardedEvent.InputTuple,
    PointsAwardedEvent.OutputTuple,
    PointsAwardedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionSubmitted"
  ): TypedContractEvent<
    PredictionSubmittedEvent.InputTuple,
    PredictionSubmittedEvent.OutputTuple,
    PredictionSubmittedEvent.OutputObject
  >;

  filters: {
    "MatchCreated(bytes32,string,string,uint64)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchResolved(bytes32,uint8)": TypedContractEvent<
      MatchResolvedEvent.InputTuple,
      MatchResolvedEvent.OutputTuple,
      MatchResolvedEvent.OutputObject
    >;
    MatchResolved: TypedContractEvent<
      MatchResolvedEvent.InputTuple,
      MatchResolvedEvent.OutputTuple,
      MatchResolvedEvent.OutputObject
    >;

    "PointsAwarded(bytes32,address,uint256)": TypedContractEvent<
      PointsAwardedEvent.InputTuple,
      PointsAwardedEvent.OutputTuple,
      PointsAwardedEvent.OutputObject
    >;
    PointsAwarded: TypedContractEvent<
      PointsAwardedEvent.InputTuple,
      PointsAwardedEvent.OutputTuple,
      PointsAwardedEvent.OutputObject
    >;

    "PredictionSubmitted(bytes32,address,uint8)": TypedContractEvent<
      PredictionSubmittedEvent.InputTuple,
      PredictionSubmittedEvent.OutputTuple,
      PredictionSubmittedEvent.OutputObject
    >;
    PredictionSubmitted: TypedContractEvent<
      PredictionSubmittedEvent.InputTuple,
      PredictionSubmittedEvent.OutputTuple,
      PredictionSubmittedEvent.OutputObject
    >;
  };
}
